# Custom Language File for Launcher Customizer

[ejs.app]
title = "Bearcraft Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/meloncafe/BearcraftLauncher"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/9Xy48CP2R6"

[ejs.settings]
sourceGithubLink = "https://github.com/meloncafe/BearcraftLauncher"
supportLink = "https://github.com/meloncafe/BearcraftLauncher/issues"

[ejs.welcome]
welcomeHeader = "WELCOME TO BEARCRAFT"
welcomeDescription = ""
welcomeDescCTA = ""
